export const STRINGS = {
  zh: {
    appName: '情绪岛',
    chooseLang: '选择你的语言',
    chooseLangSub: '之后你可以用任意语言倾诉。',
    welcome1: '写下一句此刻的心情。',
    welcome2: '如果不知道从何说起，这里有一个安静的小岛，愿意接住你所有没说出口的话。',
    featLeaf: '心形化作叶子',
    featAI: '温柔 AI 小助手',
    featLocal: '本地运行，不上云',
    start: '开始写下今天的心情',
    moodDiary: '情绪日记',
    fullRecords: '详细记录',
    about: '关于情绪岛',
    privacyWelcome: '所有数据保存在浏览器本地，本地话术库离线处理，默认不上传。',
    diaryCaption: '情绪日记',
    todaySay: '今天，我想说…',
    diaryPlaceholder: '写下此刻最真实的一句话',
    diaryHint: '写下一句话就好。有些没说出口的部分，也许会被轻轻接住。',
    trySample: '+ 试试输入「我有点难过」',
    learnAI: '了解本地情绪识别如何工作',
    continue: '继续',
    privacyDiary: '数据仅存在本地 · 情绪规则与场景话术库离线运行',
    moodFeeling: '我现在感觉…',
    companionListening: '小助手在听',
    moodContinue: '继续和小助手聊聊',
    chatTitle: '和小助手聊聊',
    saveReview: '保存并查看详情',
    chatPrivacy: '对话无轮次限制 · 仅保存在本地 · 不上传任何内容',
    chatPlaceholder: '想到哪，就说到哪…',
    aiThinking: '小助手正在想怎么接话…',
    summaryTitle: '情绪被接住的瞬间',
    summaryEmotion: '识别到的情绪',
    summaryTriggers: '触发词',
    summaryStyle: '回应方式',
    summaryStorage: '数据存储',
    summaryStorageVal: '仅本地 · 不上传',
    backDiary: '返回日记',
    saveRecord: '保存记录',
    savedTitle: '已保存到本地',
    savedMsg: '这条心情记录只存在你的浏览器里，不会上传任何内容。',
    savedOK: '好的',
    historyTitle: '我的心情记录',
    historyEmpty: '还没有保存的记录',
    historyEmptySub: '写下第一句心情，情绪岛会帮你温柔接住。',
    moodDiaryTitle: '14 天心情日记',
    moodDiarySub: '普普通通的日记，记下每天的心情起伏',
    moodRetention: '仅保留最近 14 天 · 每次倾诉贴上一枚心情',
    moodEmpty: '这一页还空着…',
    aboutTitle: '关于',
    aboutBadge: '● 本地运行 · 无需联网',
    aiDemoTitle: '本地话术引擎演示',
    send: '发送',
    home: '首页',
    back: '返回',
    me: '我',
    bot: '助手',
    turn: n => `第 ${n} 轮 · 小助手在听`,
    localAI: '本地话术库',
    localAIDesc: '完全离线 · 479 个场景模板',
    providerLabel: '小助手引擎',
  },
  en: {
    appName: 'Emotion Island',
    chooseLang: 'Choose your language',
    chooseLangSub: 'You can write in either language later.',
    welcome1: 'Write one line about how you feel.',
    welcome2: "If you don't know where to start, this quiet island is here to hold what you haven't said yet.",
    featLeaf: 'Heart to leaf',
    featAI: 'Gentle AI companion',
    featLocal: 'Runs locally',
    start: 'Start writing today',
    moodDiary: 'Mood diary',
    fullRecords: 'Full records',
    about: 'About Emotion Island',
    privacyWelcome: 'Data stays in your browser. Offline script library — nothing uploaded by default.',
    diaryCaption: 'Emotion diary',
    todaySay: 'Today, I want to say…',
    diaryPlaceholder: 'One honest line about right now',
    diaryHint: "One line is enough. What you leave unsaid might still be gently caught.",
    trySample: '+ Try "I\'m a little sad"',
    learnAI: 'How local emotion rules work',
    continue: 'Continue',
    privacyDiary: 'Stored locally only · Offline emotion rules & script library',
    moodFeeling: 'I feel…',
    companionListening: 'Companion is listening',
    moodContinue: 'Continue with companion',
    chatTitle: 'Chat with companion',
    saveReview: 'Save & review',
    chatPrivacy: 'Unlimited turns · Saved locally · Nothing uploaded',
    chatPlaceholder: 'Say whatever comes to mind…',
    aiThinking: 'Companion is thinking…',
    summaryTitle: 'The moment you were held',
    summaryEmotion: 'Emotion detected',
    summaryTriggers: 'Trigger words',
    summaryStyle: 'Response style',
    summaryStorage: 'Data storage',
    summaryStorageVal: 'Local only · never uploaded',
    backDiary: 'Back to diary',
    saveRecord: 'Save record',
    savedTitle: 'Saved locally',
    savedMsg: 'This record stays in your browser only. Nothing is uploaded.',
    savedOK: 'OK',
    historyTitle: 'My mood records',
    historyEmpty: 'No saved records yet',
    historyEmptySub: 'Write your first line — Emotion Island will gently catch it.',
    moodDiaryTitle: '14-day mood diary',
    moodDiarySub: 'A quiet diary of how your days felt',
    moodRetention: 'Keeps the last 14 days · stickers from each visit',
    moodEmpty: 'Blank page for now…',
    aboutTitle: 'About',
    aboutBadge: '● Local · no internet needed',
    aiDemoTitle: 'Local engine demo',
    send: 'Send',
    home: 'Home',
    back: 'Back',
    me: 'Me',
    bot: 'Companion',
    turn: n => `Turn ${n} · listening`,
    localAI: 'Local scripts',
    localAIDesc: 'Fully offline · 479 scenario templates',
    providerLabel: 'Companion engine',
  },
};

export const INTENT_META = {
  maskedLoneliness: { zh: '隐藏的孤独', en: 'Hidden loneliness', emoji: '🌿', style: 'breathing' },
  sadness: { zh: '低落', en: 'Low mood', emoji: '😢', style: 'wrap' },
  joy: { zh: '开心', en: 'Joy', emoji: '😊', style: 'bloom' },
  anxiety: { zh: '焦虑', en: 'Anxiety', emoji: '😰', style: 'tremble' },
  anger: { zh: '愤怒', en: 'Anger', emoji: '😤', style: 'pulse' },
  frustration: { zh: '烦躁委屈', en: 'Frustration', emoji: '😣', style: 'tighten' },
  disappointment: { zh: '失望', en: 'Disappointment', emoji: '😞', style: 'sink' },
  fear: { zh: '害怕担心', en: 'Fear', emoji: '😨', style: 'shrink' },
  exhaustion: { zh: '疲惫', en: 'Exhaustion', emoji: '😮‍💨', style: 'slow' },
  confusion: { zh: '迷茫', en: 'Confusion', emoji: '😶‍🌫️', style: 'pause' },
  neutralMasking: { zh: '中性掩饰', en: 'Neutral masking', emoji: '🌿', style: 'pause' },
  unknown: { zh: '未识别', en: 'Unrecognized', emoji: '📝', style: 'breathing' },
};

export function t(lang, key, ...args) {
  const v = STRINGS[lang]?.[key] ?? STRINGS.zh[key];
  return typeof v === 'function' ? v(...args) : v;
}
